--------------------------------------------------------
--  DDL for Table PERSONA
--------------------------------------------------------

  CREATE TABLE "MHACIENDA"."PERSONA" 
   (	"NUMCEDULA" VARCHAR2(20 BYTE), 
	"PERNOMBRE" VARCHAR2(35 BYTE), 
	"PERPRIMAPE" VARCHAR2(35 BYTE), 
	"PERSEGAPE" VARCHAR2(35 BYTE), 
	"PERDIRECCION" VARCHAR2(75 BYTE), 
	"PEREMAIL" VARCHAR2(50 BYTE), 
	"PERNUMTELEFONO" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index PK_NUMCEDULA
--------------------------------------------------------

  CREATE UNIQUE INDEX "MHACIENDA"."PK_NUMCEDULA" ON "MHACIENDA"."PERSONA" ("NUMCEDULA") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table PERSONA
--------------------------------------------------------

  ALTER TABLE "MHACIENDA"."PERSONA" ADD CONSTRAINT "PK_NUMCEDULA" PRIMARY KEY ("NUMCEDULA")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "MHACIENDA"."PERSONA" MODIFY ("PEREMAIL" NOT NULL ENABLE);
  ALTER TABLE "MHACIENDA"."PERSONA" MODIFY ("PERDIRECCION" NOT NULL ENABLE);
  ALTER TABLE "MHACIENDA"."PERSONA" MODIFY ("PERSEGAPE" NOT NULL ENABLE);
  ALTER TABLE "MHACIENDA"."PERSONA" MODIFY ("PERPRIMAPE" NOT NULL ENABLE);
  ALTER TABLE "MHACIENDA"."PERSONA" MODIFY ("PERNOMBRE" NOT NULL ENABLE);
  ALTER TABLE "MHACIENDA"."PERSONA" MODIFY ("NUMCEDULA" NOT NULL ENABLE);
