--------------------------------------------------------
--  DDL for Table REGISTRO
--------------------------------------------------------

  CREATE TABLE "MHACIENDA"."REGISTRO" 
   (	"NUMREGISTRO" VARCHAR2(20 BYTE), 
	"IDENTIFICACION" VARCHAR2(20 BYTE), 
	"FECHAREGISTRO" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index PK_NUMREGISTRO
--------------------------------------------------------

  CREATE UNIQUE INDEX "MHACIENDA"."PK_NUMREGISTRO" ON "MHACIENDA"."REGISTRO" ("NUMREGISTRO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table REGISTRO
--------------------------------------------------------

  ALTER TABLE "MHACIENDA"."REGISTRO" ADD CONSTRAINT "PK_NUMREGISTRO" PRIMARY KEY ("NUMREGISTRO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "MHACIENDA"."REGISTRO" MODIFY ("FECHAREGISTRO" NOT NULL ENABLE);
  ALTER TABLE "MHACIENDA"."REGISTRO" MODIFY ("IDENTIFICACION" NOT NULL ENABLE);
  ALTER TABLE "MHACIENDA"."REGISTRO" MODIFY ("NUMREGISTRO" NOT NULL ENABLE);
